/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ state, useSnapshot }) {
  const snap = useSnapshot(state);

  const [hovered, set] = useState(null);
  const group = useRef();
  const { nodes, materials } = useGLTF("/cardraco.gltf");
  return (
    <group
      ref={group}
      dispose={null}
      onPointerOver={(e) => (e.stopPropagation(), set(e.object.material.name))}
      onPointerOut={(e) => e.intersections.length === 0 && set(null)}
      onPointerMissed={() => (state.current = null)}
      onPointerDown={(e) => (
        e.stopPropagation(), (state.current = e.object.material.name)
      )}
    >
      >
      <group
        rotation={[-Math.PI / 2, 0, -2.25]}
        scale={0.0068}
        position={[0, -0.5, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-1.58, 0, 0]} scale={[300, 100, 50]}>
            <mesh
              geometry={nodes.Frame_Black_0.geometry}
              material={nodes.Frame_Black_0.material}
              castShadow
            />
            <mesh
              geometry={nodes.Frame_Brown_0.geometry}
              material={materials.Brown}
              material-color={state.items.Brown}
              castShadow
            />
            <mesh
              geometry={nodes.Frame_Dark_brown_0.geometry}
              material={materials.Dark_brown}
              material-color={state.items.Dark_brown}
              castShadow
            />
            <mesh
              geometry={nodes.Frame_Dark_brown_handle_0.geometry}
              material={materials.Dark_brown_handle}
              castShadow
            />
            <mesh
              geometry={nodes.Frame_Glass_0.geometry}
              material={materials.Glass}
              material-color={state.items.Glass}
              castShadow
            />
            <mesh
              geometry={nodes.Frame_Glass_trailer_0.geometry}
              material={materials.Glass_trailer}
              castShadow
            />
            <mesh
              geometry={nodes.Frame_Light_0.geometry}
              material={materials.Light}
            />
            <mesh
              geometry={nodes.Frame_Light_black_0.geometry}
              material={nodes.Frame_Light_black_0.material}
              castShadow
            />
            <mesh
              geometry={nodes.Frame_Light_red_0.geometry}
              material={materials.Light_red}
              castShadow
            />
            <mesh
              geometry={nodes.Frame_Orange_0.geometry}
              material={materials.Orange}
              material-color={state.items.Orange}
              castShadow
            />
          </group>
          <group
            position={[155.62, 9.27, -127.28]}
            rotation={[0, 0, -1.4]}
            scale={[50.1, 50.1, 27.01]}
          >
            <mesh
              geometry={nodes.Front_wheel_Black_0.geometry}
              material={nodes.Front_wheel_Black_0.material}
              material-color={state.items.Black}
              castShadow
            />
            <mesh
              geometry={nodes.Front_wheel_Light_black_0.geometry}
              material={nodes.Front_wheel_Light_black_0.material}
            />
          </group>
          <group
            position={[155.62, 9.27, 127.28]}
            rotation={[Math.PI, 0, 1.31]}
            scale={[50.1, 50.1, 27.01]}
          >
            <mesh
              geometry={nodes.Front_wheel001_Black_0.geometry}
              material={nodes.Front_wheel001_Black_0.material}
              castShadow
            />
            <mesh
              geometry={nodes.Front_wheel001_Light_black_0.geometry}
              material={nodes.Front_wheel001_Light_black_0.material}
            />
          </group>
          <group
            position={[-128.51, 14.27, -125.98]}
            rotation={[0, 0, -2.16]}
            scale={[55.11, 55.11, 29.62]}
          >
            <mesh
              geometry={nodes.Rear_wheel_Black_0.geometry}
              material={nodes.Rear_wheel_Black_0.material}
              castShadow
            />
            <mesh
              geometry={nodes.Rear_wheel_Light_black_0.geometry}
              material={nodes.Rear_wheel_Light_black_0.material}
            />
          </group>
          <group
            position={[-128.51, 14.27, 125.98]}
            rotation={[Math.PI, 0, 2.13]}
            scale={[55.11, 55.11, 29.62]}
          >
            <mesh
              geometry={nodes.Rear_wheel001_Black_0.geometry}
              material={nodes.Rear_wheel001_Black_0.material}
              castShadow
            />
            <mesh
              geometry={nodes.Rear_wheel001_Light_black_0.geometry}
              material={nodes.Rear_wheel001_Light_black_0.material}
            />
          </group>
          <group
            position={[155.62, 20.26, -81.85]}
            rotation={[-0.2, Math.PI / 2, 0]}
            scale={2.8}
          >
            <mesh
              geometry={nodes.Spring_Black_0.geometry}
              material={nodes.Spring_Black_0.material}
            />
            <mesh
              geometry={nodes.Spring_Light_black_0.geometry}
              material={nodes.Spring_Light_black_0.material}
            />
          </group>
          <group
            position={[-128.51, 20.26, -81.85]}
            rotation={[-0.2, Math.PI / 2, 0]}
            scale={2.8}
          >
            <mesh
              geometry={nodes.Spring001_Black_0.geometry}
              material={nodes.Spring001_Black_0.material}
            />
            <mesh
              geometry={nodes.Spring001_Light_black_0.geometry}
              material={nodes.Spring001_Light_black_0.material}
            />
          </group>
          <group
            position={[155.62, 21.19, 82.07]}
            rotation={[0.22, -Math.PI / 2, 0]}
            scale={2.8}
          >
            <mesh
              geometry={nodes.Spring002_Black_0.geometry}
              material={nodes.Spring002_Black_0.material}
            />
            <mesh
              geometry={nodes.Spring002_Light_black_0.geometry}
              material={nodes.Spring002_Light_black_0.material}
            />
          </group>
          <group
            position={[-128.51, 21.19, 82.07]}
            rotation={[0.22, -Math.PI / 2, 0]}
            scale={2.8}
          >
            <mesh
              geometry={nodes.Spring003_Black_0.geometry}
              material={nodes.Spring003_Black_0.material}
            />
            <mesh
              geometry={nodes.Spring003_Light_black_0.geometry}
              material={nodes.Spring003_Light_black_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/cardraco.gltf");
